// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import starlightUtils from "@lorenzo_lewis/starlight-utils";

import sitemap from "@astrojs/sitemap";

// https://astro.build/config
export default defineConfig({
  site: "https://gin-gonic.com",

  integrations: [
    starlight({
      plugins: [
        starlightUtils({
          multiSidebar: {
            switcherStyle: "horizontalList",
          },
        }),
      ],

      title: "Gin Web Framework",
      favicon: "/favicon.ico",
      logo: {
        src: "./src/assets/gin.png",
      },

      defaultLocale: "en",
      locales: {
        en: {
          label: "English",
          lang: "en",
        },
        es: {
          label: "Español",
          lang: "es",
        },
        fa: {
          label: "Persian",
          lang: "fa",
        },
        id: {
          label: "Bahasa Indonesia",
          lang: "id",
        },
        ja: {
          label: "日本語",
          lang: "ja",
        },
        "ko-kr": {
          label: "한국어",
          lang: "ko-KR",
        },
        pt: {
          label: "Português",
          lang: "pt",
        },
        ru: {
          label: "Russian",
          lang: "ru",
        },
        tr: {
          label: "Turkish",
          lang: "tr",
        },
        "zh-cn": {
          label: "简体中文",
          lang: "zh-CN",
        },
        "zh-tw": {
          label: "繁體中文",
          lang: "zh-TW",
        },
        ar: {
          label: "عربي",
          lang: "ar",
        },
      },

      social: {
        github: "https://github.com/gin-gonic/gin",
      },
      sidebar: [
        {
          label: "Docs",
          translations: {
            es: "Documentación",
            fa: "مستندات",
            id: "Dokumentasi",
            ja: "ドキュメント",
            "ko-KR": "문서",
            pt: "Documentação",
            ru: "Документация",
            tr: "Belgeler",
            "zh-CN": "文档",
            "zh-TW": "文件",
            ar: "المستندات",
          },
          items: [
            {
              label: "Introduction",
              translations: {
                es: "Introducción",
                fa: "معرفی",
                id: "Pengantar",
                ja: "はじめに",
                "ko-KR": "소개",
                pt: "Introdução",
                ru: "Введение",
                tr: "Giriş",
                "zh-CN": "介绍",
                "zh-TW": "介紹",
                ar: "مقدمة",
              },
              slug: "docs/introduction",
            },
            {
              label: "Quickstart",
              translations: {
                es: "Inicio rápido",
                fa: "شروع سریع",
                id: "Mulai Cepat",
                ja: "クイックスタート",
                "ko-KR": "빠른 시작",
                pt: "Início rápido",
                ru: "Быстрый старт",
                tr: "Hızlı Başlangıç",
                "zh-CN": "快速开始",
                "zh-TW": "快速開始",
                ar: "البداية السريعة",
              },
              slug: "docs/quickstart",
            },
            {
              label: "Routing",
              translations: {
                es: "Enrutamiento",
                fa: "مسیریابی",
                id: "Routing",
                ja: "ルーティング",
                "ko-KR": "라우팅",
                pt: "Roteamento",
                ru: "Маршрутизация",
                tr: "Yönlendirme",
                "zh-CN": "路由",
                "zh-TW": "路由",
                ar: "التوجيه",
              },
              items: [
                { slug: "docs/routing/http-method" },
                { slug: "docs/routing/param-in-path" },
                { slug: "docs/routing/querystring-param" },
                { slug: "docs/routing" },
                { slug: "docs/routing/multipart-urlencoded-form" },
                { slug: "docs/routing/query-and-post-form" },
                { slug: "docs/routing/map-as-querystring-or-postform" },
                {
                  label: "Upload Files",
                  translations: {
                    es: "Subir archivos",
                    fa: "آپلود فایل‌ها",
                    id: "Upload file",
                    ja: "ファイルアップロード",
                    "ko-KR": "파일 업로드",
                    pt: "Upload de arquivos",
                    ru: "Загрузка файлов",
                    tr: "Dosya yükleme",
                    "zh-CN": "文件上传",
                    "zh-TW": "檔案上傳",
                    ar: "رفع الملفات",
                  },
                  items: [
                    { slug: "docs/routing/upload-file" },
                    { slug: "docs/routing/upload-file/single-file" },
                    { slug: "docs/routing/upload-file/multiple-file" },
                    { slug: "docs/routing/upload-file/limit-bytes" },
                  ],
                },
                { slug: "docs/routing/grouping-routes" },
                { slug: "docs/routing/redirects" },
                { slug: "docs/routing/api-design" },
              ],
            },
            {
              label: "Binding",
              translations: {
                es: "Vinculación",
                fa: "اتصال داده",
                id: "Binding",
                ja: "バインディング",
                "ko-KR": "바인딩",
                pt: "Binding",
                ru: "Привязка данных",
                tr: "Bağlama",
                "zh-CN": "数据绑定",
                "zh-TW": "資料綁定",
                ar: "الربط",
              },
              autogenerate: { directory: "docs/binding" },
            },
            {
              label: "Rendering",
              translations: {
                es: "Renderizado",
                fa: "رندرینگ",
                id: "Rendering",
                ja: "レンダリング",
                "ko-KR": "렌더링",
                pt: "Renderização",
                ru: "Рендеринг",
                tr: "Render",
                "zh-CN": "渲染",
                "zh-TW": "渲染",
                ar: "العرض",
              },
              autogenerate: { directory: "docs/rendering" },
            },
            {
              label: "Middleware",
              translations: {
                es: "Middleware",
                fa: "میان‌افزار",
                id: "Middleware",
                ja: "ミドルウェア",
                "ko-KR": "미들웨어",
                pt: "Middleware",
                ru: "Промежуточное ПО",
                tr: "Ara Yazılım",
                "zh-CN": "中间件",
                "zh-TW": "中介軟體",
                ar: "البرمجيات الوسيطة",
              },
              autogenerate: { directory: "docs/middleware" },
            },
            {
              label: "Logging",
              translations: {
                es: "Registro",
                fa: "ثبت وقایع",
                id: "Logging",
                ja: "ロギング",
                "ko-KR": "로깅",
                pt: "Logging",
                ru: "Логирование",
                tr: "Günlükleme",
                "zh-CN": "日志",
                "zh-TW": "日誌",
                ar: "التسجيل",
              },
              autogenerate: { directory: "docs/logging" },
            },
            {
              label: "Server Configuration",
              translations: {
                es: "Configuración del servidor",
                fa: "پیکربندی سرور",
                id: "Konfigurasi Server",
                ja: "サーバー設定",
                "ko-KR": "서버 설정",
                pt: "Configuração do servidor",
                ru: "Настройка сервера",
                tr: "Sunucu Yapılandırması",
                "zh-CN": "服务器配置",
                "zh-TW": "伺服器設定",
                ar: "إعدادات الخادم",
              },
              autogenerate: { directory: "docs/server-config" },
            },
            {
              label: "Testing",
              translations: {
                es: "Pruebas",
                fa: "تست",
                id: "Pengujian",
                ja: "テスト",
                "ko-KR": "테스트",
                pt: "Testes",
                ru: "Тестирование",
                tr: "Test",
                "zh-CN": "测试",
                "zh-TW": "測試",
                ar: "الاختبار",
              },
              slug: "docs/testing",
            },
            {
              label: "Deployment",
              translations: {
                es: "Despliegue",
                fa: "استقرار",
                id: "Deployment",
                ja: "デプロイ",
                "ko-KR": "배포",
                pt: "Implantação",
                ru: "Развёртывание",
                tr: "Dağıtım",
                "zh-CN": "部署",
                "zh-TW": "部署",
                ar: "النشر",
              },
              slug: "docs/deployment",
            },
            {
              label: "Build Tags",
              translations: {
                es: "Etiquetas de compilación",
                fa: "تگ‌های ساخت",
                id: "Build Tags",
                ja: "ビルドタグ",
                "ko-KR": "빌드 태그",
                pt: "Tags de build",
                ru: "Теги сборки",
                tr: "Derleme Etiketleri",
                "zh-CN": "构建标签",
                "zh-TW": "建置標籤",
                ar: "علامات البناء",
              },
              autogenerate: { directory: "docs/build-tags" },
            },
            {
              label: "Benchmarks",
              translations: {
                es: "Rendimiento",
                fa: "معیارها",
                id: "Benchmark",
                ja: "ベンチマーク",
                "ko-KR": "벤치마크",
                pt: "Benchmarks",
                ru: "Бенчмарки",
                tr: "Karşılaştırmalar",
                "zh-CN": "基准测试",
                "zh-TW": "效能測試",
                ar: "اختبارات الأداء",
              },
              slug: "docs/benchmarks",
            },
            {
              label: "Learning Resources",
              translations: {
                es: "Recursos de aprendizaje",
                fa: "منابع آموزشی",
                id: "Sumber Belajar",
                ja: "学習リソース",
                "ko-KR": "학습 자료",
                pt: "Recursos de aprendizado",
                ru: "Учебные ресурсы",
                tr: "Öğrenme Kaynakları",
                "zh-CN": "学习资源",
                "zh-TW": "學習資源",
                ar: "مصادر التعلم",
              },
              slug: "docs/learning-resources",
            },
            {
              label: "Users",
              translations: {
                es: "Usuarios",
                fa: "کاربران",
                id: "Pengguna",
                ja: "ユーザー",
                "ko-KR": "사용자",
                pt: "Usuários",
                ru: "Пользователи",
                tr: "Kullanıcılar",
                "zh-CN": "用户",
                "zh-TW": "使用者",
                ar: "المستخدمون",
              },
              slug: "docs/users",
            },
            {
              label: "FAQ",
              translations: {
                es: "Preguntas frecuentes",
                fa: "سوالات متداول",
                id: "FAQ",
                ja: "よくある質問",
                "ko-KR": "자주 묻는 질문",
                pt: "Perguntas frequentes",
                ru: "Часто задаваемые вопросы",
                tr: "SSS",
                "zh-CN": "常见问题",
                "zh-TW": "常見問題",
                ar: "الأسئلة الشائعة",
              },
              autogenerate: { directory: "docs/faq" },
            },
          ],
        },
        {
          label: "Blog",
          translations: {
            es: "Blog",
            fa: "وبلاگ",
            id: "Blog",
            ja: "ブログ",
            "ko-KR": "블로그",
            pt: "Blog",
            ru: "Блог",
            tr: "Blog",
            "zh-CN": "博客",
            "zh-TW": "部落格",
            ar: "المدونة",
          },
          autogenerate: { directory: "blog" },
        },
      ],
      expressiveCode: {
        themes: ["github-dark", "github-light"],
      },
      editLink: {
        baseUrl: "https://github.com/gin-gonic/website/edit/master/",
      },
      customCss: ["./src/styles/custom.css"],
      lastUpdated: true,
      credits: false, // Opcional
    }),
    sitemap(),
  ],
});
